name: Sync with HuggingFace Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: sync
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: Crayon112/substore-hfspace-sync
        huggingface_repo_id: Crayon112/Substore
        repo_type: space
        space_sdk: docker
        hf_token: ${{ secrets.HF_TOKEN }}
