name: Sync with HuggingFace Hub

on:
  schedule:
    - cron: "* */6 3 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update Dockerfile
        run: |
          NOW=$(date +"%Y-%m-%d %H:%M:%S");
          sed -i "\$s/.*/# Release: ${NOW}/" Dockerfile
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHubActions"
          git add Dockerfile
          git commit -m "version: ${NOW}"
          git push https://${{ secrets.PAT }}@github.com/Crayon112/substore-hfspace-sync.git HEAD:master
  
  sync:
    needs: update
    runs-on: ubuntu-latest
    steps:
    - name: Sync HuggingFace Space
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: Crayon112/substore-hfspace-sync
        huggingface_repo_id: Crayon112/Substore
        repo_type: space
        space_sdk: docker
        hf_token: ${{ secrets.HF_TOKEN }}
